use_frameworks!
platform :ios, '10.0'

target 'TKControlsLib_Example' do
  pod 'TKControlsLib', :path => '../', :subspecs => ['Common', 'CommonControl', 'CommonUI']

  target 'TKControlsLib_Tests' do
    inherit! :search_paths

  end
end
